// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDPhr39UM8pOW33TaKmdNN7aoXPiX5ocQ',
    appId: '1:562481393831:web:5873648a5fef8a00bdab82',
    messagingSenderId: '562481393831',
    projectId: 'appliradio-961de',
    authDomain: 'appliradio-961de.firebaseapp.com',
    databaseURL: 'https://appliradio-961de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appliradio-961de.appspot.com',
    measurementId: 'G-RD3XG4G94Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbxpNpkppycPrVbA5Z3ZxK-M00KJj-PUA',
    appId: '1:562481393831:android:6171605440f7f3c3bdab82',
    messagingSenderId: '562481393831',
    projectId: 'appliradio-961de',
    databaseURL: 'https://appliradio-961de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appliradio-961de.appspot.com',
  );
}
